version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: ingestiq_postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-ingestiq_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    shm_size: 256m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-webserver:
    image: apache/airflow:2.9.1
    env_file:
      -  .env
    container_name: airflow_webserver
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-ingestiq_db}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT: 300
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
      AIRFLOW__LOGGING__REMOTE_LOGGING: "False"
    volumes:
      - ./src:/opt/airflow/dags/src
      - ./dags:/opt/airflow/dags
      - ./data:/app/data
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create
          --username ${AIRFLOW_ADMIN_USER}
          --firstname Admin
          --lastname User
          --role Admin
          --email admin@example.com
          --password ${AIRFLOW_ADMIN_PASSWORD} || true &&
        airflow webserver
      "
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.9.1
    container_name: airflow_scheduler
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-ingestiq_db}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
      AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
      AIRFLOW__LOGGING__REMOTE_LOGGING: "False"
    volumes:
      - ./src:/opt/airflow/dags/src
      - ./dags:/opt/airflow/dags
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
      airflow-webserver:
        condition: service_started
    command: airflow scheduler
    restart: always

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ingestiq_dashboard
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB:-ingestiq_db}
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
    volumes:
     - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
    command: streamlit run src/dashboard/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ingestiq_api
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB:-ingestiq_db}
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
    volumes:
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn src.dashboard.server:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    restart: always

volumes:
  postgres_data:
